// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;
import ballerinax/sap;

# You can use these APIs to access the personal information of an employee including emergency contact information, social media accounts, email address, and non-effective-dated biographical information such as date of birth, country of birth and national identification card information.
# 
#  You can find your company's API server in [List of API Servers in SAP SuccessFactors.](https://help.sap.com/viewer/d599f15995d348a1b45ba5603e2aba9b/LATEST/en-US/af2b8d5437494b12be88fe374eba75b6.html)
public isolated client class Client {
    final sap:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string hostname, int port = 443) returns error? {
string serviceUrl = string `https://${hostname}:${port}/successfactors/odata/v2`;
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # Get entities from PerEmergencyContacts
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listPerEmergencyContactss(map<string|string[]> headers = {}, *ListPerEmergencyContactssQueries queries) returns Wrapper|error {
        string resourcePath = string `/PerEmergencyContacts`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entity from PerEmergencyContacts by key
    #
    # + name - key: name
    # + personIdExternal - key: personIdExternal
    # + relationship - key: relationship
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getPerEmergencyContacts(string name, string personIdExternal, string relationship, map<string|string[]> headers = {}, *GetPerEmergencyContactsQueries queries) returns PerEmergencyContacts|error {
        string resourcePath = string `/PerEmergencyContacts(name='${getEncodedUri(name)}',personIdExternal='${getEncodedUri(personIdExternal)}',relationship='${getEncodedUri(relationship)}')`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entities from PerPhone
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listPerPhones(map<string|string[]> headers = {}, *ListPerPhonesQueries queries) returns Wrapper_1|error {
        string resourcePath = string `/PerPhone`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entity from PerPhone by key
    #
    # + personIdExternal - key: personIdExternal
    # + phoneType - key: phoneType
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getPerPhone(string personIdExternal, string phoneType, map<string|string[]> headers = {}, *GetPerPhoneQueries queries) returns PerPhone|error {
        string resourcePath = string `/PerPhone(personIdExternal='${getEncodedUri(personIdExternal)}',phoneType='${getEncodedUri(phoneType)}')`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entities from PersonKey
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listPersonKeys(map<string|string[]> headers = {}, *ListPersonKeysQueries queries) returns Wrapper_2|error {
        string resourcePath = string `/PersonKey`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entity from PersonKey by key
    #
    # + personIdExternal - key: personIdExternal
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getPersonKey(string personIdExternal, map<string|string[]> headers = {}, *GetPersonKeyQueries queries) returns PersonKey|error {
        string resourcePath = string `/PersonKey('${getEncodedUri(personIdExternal)}')`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entities from PerPersonal
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listPerPersonals(map<string|string[]> headers = {}, *ListPerPersonalsQueries queries) returns Wrapper_3|error {
        string resourcePath = string `/PerPersonal`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entity from PerPersonal by key
    #
    # + personIdExternal - key: personIdExternal
    # + startDate - key: startDate
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getPerPersonal(string personIdExternal, string startDate, map<string|string[]> headers = {}, *GetPerPersonalQueries queries) returns PerPersonal|error {
        string resourcePath = string `/PerPersonal(personIdExternal='${getEncodedUri(personIdExternal)}',startDate=${getEncodedUri(startDate)})`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entities from PerSocialAccount
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listPerSocialAccounts(map<string|string[]> headers = {}, *ListPerSocialAccountsQueries queries) returns Wrapper_4|error {
        string resourcePath = string `/PerSocialAccount`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entity from PerSocialAccount by key
    #
    # + domain - key: domain
    # + personIdExternal - key: personIdExternal
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getPerSocialAccount(string domain, string personIdExternal, map<string|string[]> headers = {}, *GetPerSocialAccountQueries queries) returns PerSocialAccount|error {
        string resourcePath = string `/PerSocialAccount(domain='${getEncodedUri(domain)}',personIdExternal='${getEncodedUri(personIdExternal)}')`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entities from PerPerson
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listPerPersons(map<string|string[]> headers = {}, *ListPerPersonsQueries queries) returns Wrapper_5|error {
        string resourcePath = string `/PerPerson`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entity from PerPerson by key
    #
    # + personIdExternal - key: personIdExternal
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getPerPerson(string personIdExternal, map<string|string[]> headers = {}, *GetPerPersonQueries queries) returns PerPerson|error {
        string resourcePath = string `/PerPerson('${getEncodedUri(personIdExternal)}')`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entities from PerPersonRelationship
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listPerPersonRelationships(map<string|string[]> headers = {}, *ListPerPersonRelationshipsQueries queries) returns Wrapper_6|error {
        string resourcePath = string `/PerPersonRelationship`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entity from PerPersonRelationship by key
    #
    # + personIdExternal - key: personIdExternal
    # + relatedPersonIdExternal - key: relatedPersonIdExternal
    # + startDate - key: startDate
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getPerPersonRelationship(string personIdExternal, string relatedPersonIdExternal, string startDate, map<string|string[]> headers = {}, *GetPerPersonRelationshipQueries queries) returns PerPersonRelationship|error {
        string resourcePath = string `/PerPersonRelationship(personIdExternal='${getEncodedUri(personIdExternal)}',relatedPersonIdExternal='${getEncodedUri(relatedPersonIdExternal)}',startDate=${getEncodedUri(startDate)})`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entities from PerEmail
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listPerEmails(map<string|string[]> headers = {}, *ListPerEmailsQueries queries) returns Wrapper_7|error {
        string resourcePath = string `/PerEmail`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entity from PerEmail by key
    #
    # + emailType - key: emailType
    # + personIdExternal - key: personIdExternal
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getPerEmail(string emailType, string personIdExternal, map<string|string[]> headers = {}, *GetPerEmailQueries queries) returns PerEmail|error {
        string resourcePath = string `/PerEmail(emailType='${getEncodedUri(emailType)}',personIdExternal='${getEncodedUri(personIdExternal)}')`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entities from HrisEmergencyContactAddressDEFLT
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listHrisEmergencyContactAddressDEFLTs(map<string|string[]> headers = {}, *ListHrisEmergencyContactAddressDEFLTsQueries queries) returns Wrapper_8|error {
        string resourcePath = string `/HrisEmergencyContactAddressDEFLT`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entity from HrisEmergencyContactAddressDEFLT by key
    #
    # + addressId - key: addressId
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getHrisEmergencyContactAddressDEFLT(string addressId, map<string|string[]> headers = {}, *GetHrisEmergencyContactAddressDEFLTQueries queries) returns HrisEmergencyContactAddressDEFLT|error {
        string resourcePath = string `/HrisEmergencyContactAddressDEFLT('${getEncodedUri(addressId)}')`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entities from PerNationalId
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listPerNationalIds(map<string|string[]> headers = {}, *ListPerNationalIdsQueries queries) returns Wrapper_9|error {
        string resourcePath = string `/PerNationalId`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entity from PerNationalId by key
    #
    # + cardType - key: cardType
    # + country - key: country
    # + personIdExternal - key: personIdExternal
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getPerNationalId(string cardType, string country, string personIdExternal, map<string|string[]> headers = {}, *GetPerNationalIdQueries queries) returns PerNationalId|error {
        string resourcePath = string `/PerNationalId(cardType='${getEncodedUri(cardType)}',country='${getEncodedUri(country)}',personIdExternal='${getEncodedUri(personIdExternal)}')`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entities from PerNationalIdWithValidityPeriod
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listPerNationalIdWithValidityPeriods(map<string|string[]> headers = {}, *ListPerNationalIdWithValidityPeriodsQueries queries) returns Wrapper_10|error {
        string resourcePath = string `/PerNationalIdWithValidityPeriod`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entity from PerNationalIdWithValidityPeriod by key
    #
    # + recordId - key: recordId
    # + personIdExternal - key: personIdExternal
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getPerNationalIdWithValidityPeriod(string recordId, string personIdExternal, map<string|string[]> headers = {}, *GetPerNationalIdWithValidityPeriodQueries queries) returns PerNationalIdWithValidityPeriod|error {
        string resourcePath = string `/PerNationalIdWithValidityPeriod(recordId='${getEncodedUri(recordId)}',personIdExternal='${getEncodedUri(personIdExternal)}')`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entities from PerAddressDEFLT
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listPerAddressDEFLTs(map<string|string[]> headers = {}, *ListPerAddressDEFLTsQueries queries) returns Wrapper_11|error {
        string resourcePath = string `/PerAddressDEFLT`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entity from PerAddressDEFLT by key
    #
    # + addressType - key: addressType
    # + personIdExternal - key: personIdExternal
    # + startDate - key: startDate
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getPerAddressDEFLT(string addressType, string personIdExternal, string startDate, map<string|string[]> headers = {}, *GetPerAddressDEFLTQueries queries) returns PerAddressDEFLT|error {
        string resourcePath = string `/PerAddressDEFLT(addressType='${getEncodedUri(addressType)}',personIdExternal='${getEncodedUri(personIdExternal)}',startDate=${getEncodedUri(startDate)})`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Invoke action generateNextPersonID
    #
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function creategenerateNextPersonID(map<string|string[]> headers = {}) returns Result|error {
        string resourcePath = string `/generateNextPersonID`;
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get entities from NameFormatGO
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listNameFormatGOs(map<string|string[]> headers = {}, *ListNameFormatGOsQueries queries) returns Wrapper_12|error {
        string resourcePath = string `/NameFormatGO`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entity from NameFormatGO by key
    #
    # + externalCode - key: externalCode
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getNameFormatGO(string externalCode, map<string|string[]> headers = {}, *GetNameFormatGOQueries queries) returns NameFormatGO|error {
        string resourcePath = string `/NameFormatGO('${getEncodedUri(externalCode)}')`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entities from NameElementGO
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listNameElementGOs(map<string|string[]> headers = {}, *ListNameElementGOsQueries queries) returns Wrapper_13|error {
        string resourcePath = string `/NameElementGO`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entity from NameElementGO by key
    #
    # + NameFormatGO_externalCode - key: NameFormatGO_externalCode
    # + externalCode - key: externalCode
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getNameElementGO(string NameFormatGO_externalCode, string externalCode, map<string|string[]> headers = {}, *GetNameElementGOQueries queries) returns NameElementGO|error {
        string resourcePath = string `/NameElementGO(NameFormatGO_externalCode='${getEncodedUri(NameFormatGO_externalCode)}',externalCode='${getEncodedUri(externalCode)}')`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entities from PerBiographicalInfoLocBRA
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listPerBiographicalInfoLocBRAs(map<string|string[]> headers = {}, *ListPerBiographicalInfoLocBRAsQueries queries) returns Wrapper_14|error {
        string resourcePath = string `/PerBiographicalInfoLocBRA`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entity from PerBiographicalInfoLocBRA by key
    #
    # + country - key: country
    # + personIdExternal - key: personIdExternal
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getPerBiographicalInfoLocBRA(string country, string personIdExternal, map<string|string[]> headers = {}, *GetPerBiographicalInfoLocBRAQueries queries) returns PerBiographicalInfoLocBRA|error {
        string resourcePath = string `/PerBiographicalInfoLocBRA(country='${getEncodedUri(country)}',personIdExternal='${getEncodedUri(personIdExternal)}')`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entities from PerBiographicalInfoLocCHL
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listPerBiographicalInfoLocCHLs(map<string|string[]> headers = {}, *ListPerBiographicalInfoLocCHLsQueries queries) returns Wrapper_15|error {
        string resourcePath = string `/PerBiographicalInfoLocCHL`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entity from PerBiographicalInfoLocCHL by key
    #
    # + country - key: country
    # + personIdExternal - key: personIdExternal
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getPerBiographicalInfoLocCHL(string country, string personIdExternal, map<string|string[]> headers = {}, *GetPerBiographicalInfoLocCHLQueries queries) returns PerBiographicalInfoLocCHL|error {
        string resourcePath = string `/PerBiographicalInfoLocCHL(country='${getEncodedUri(country)}',personIdExternal='${getEncodedUri(personIdExternal)}')`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entities from PerBiographicalInfoLocFRA
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listPerBiographicalInfoLocFRAs(map<string|string[]> headers = {}, *ListPerBiographicalInfoLocFRAsQueries queries) returns Wrapper_16|error {
        string resourcePath = string `/PerBiographicalInfoLocFRA`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entity from PerBiographicalInfoLocFRA by key
    #
    # + country - key: country
    # + personIdExternal - key: personIdExternal
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getPerBiographicalInfoLocFRA(string country, string personIdExternal, map<string|string[]> headers = {}, *GetPerBiographicalInfoLocFRAQueries queries) returns PerBiographicalInfoLocFRA|error {
        string resourcePath = string `/PerBiographicalInfoLocFRA(country='${getEncodedUri(country)}',personIdExternal='${getEncodedUri(personIdExternal)}')`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entities from PerBiographicalInfoLocITA
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listPerBiographicalInfoLocITAs(map<string|string[]> headers = {}, *ListPerBiographicalInfoLocITAsQueries queries) returns Wrapper_17|error {
        string resourcePath = string `/PerBiographicalInfoLocITA`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entity from PerBiographicalInfoLocITA by key
    #
    # + country - key: country
    # + personIdExternal - key: personIdExternal
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getPerBiographicalInfoLocITA(string country, string personIdExternal, map<string|string[]> headers = {}, *GetPerBiographicalInfoLocITAQueries queries) returns PerBiographicalInfoLocITA|error {
        string resourcePath = string `/PerBiographicalInfoLocITA(country='${getEncodedUri(country)}',personIdExternal='${getEncodedUri(personIdExternal)}')`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entities from PerBiographicalInfoLocVEN
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listPerBiographicalInfoLocVENs(map<string|string[]> headers = {}, *ListPerBiographicalInfoLocVENsQueries queries) returns Wrapper_18|error {
        string resourcePath = string `/PerBiographicalInfoLocVEN`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get entity from PerBiographicalInfoLocVEN by key
    #
    # + country - key: country
    # + personIdExternal - key: personIdExternal
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getPerBiographicalInfoLocVEN(string country, string personIdExternal, map<string|string[]> headers = {}, *GetPerBiographicalInfoLocVENQueries queries) returns PerBiographicalInfoLocVEN|error {
        string resourcePath = string `/PerBiographicalInfoLocVEN(country='${getEncodedUri(country)}',personIdExternal='${getEncodedUri(personIdExternal)}')`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }
}
