// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.org).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

public type PerNationalId record {
    SFOData\.PerNationalId d?;
};

public type SFOData\.PerBiographicalInfoLocITA record {
    string country?;
    string personIdExternal?;
};

public type RelatedCollectionSFOData_NameElementGO record {
    SFOData\.NameElementGO[] results?;
};

public type PerBiographicalInfoLocVEN record {
    SFOData\.PerBiographicalInfoLocVEN d?;
};

public type CollectionofPerBiographicalInfoLocVEN record {
    SFOData\.PerBiographicalInfoLocVEN[] results?;
};

public type CollectionofNameElementGO record {
    SFOData\.NameElementGO[] results?;
};

public type SFOData\.PerBiographicalInfoLocVEN record {
    string country?;
    string personIdExternal?;
};

public type SFOData\.PerPhone record {
    string personIdExternal?;
    string phoneType?;
    SFOData\.PerPerson personNav?;
};

public type PerBiographicalInfoLocCHL record {
    SFOData\.PerBiographicalInfoLocCHL d?;
};

public type CollectionofPerBiographicalInfoLocITA record {
    SFOData\.PerBiographicalInfoLocITA[] results?;
};

# Represents the Queries record for the operation: listPerBiographicalInfoLocFRAs
public type ListPerBiographicalInfoLocFRAsQueries record {
    # Skip the first n items, see [OData Paging - Skip](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$skip?;
    # Show only the first n items, see [OData Paging - Top](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$top = 20;
    # Filter items by property values, see [OData Filtering](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$filter?;
    # Search items by search phrases, see [OData Searching](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$search?;
    # Order items by property values, see [OData Sorting](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("country"|"country desc"|"createdBy"|"createdBy desc"|"createdDateTime"|"createdDateTime desc"|"createdOn"|"createdOn desc"|"customString1"|"customString1 desc"|"lastModifiedBy"|"lastModifiedBy desc"|"lastModifiedDateTime"|"lastModifiedDateTime desc"|"lastModifiedOn"|"lastModifiedOn desc"|"operation"|"operation desc"|"personIdExternal"|"personIdExternal desc"|"placeOfBirth"|"placeOfBirth desc"|"regionOfBirth"|"regionOfBirth desc")[] \$orderby?;
    # Include count of items, see [OData Count](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    boolean \$count?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("country"|"createdBy"|"createdDateTime"|"createdOn"|"customString1"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"operation"|"personIdExternal"|"placeOfBirth"|"regionOfBirth")[] \$select?;
};

public type HrisEmergencyContactAddressDEFLT record {
    SFOData\.HrisEmergencyContactAddressDEFLT d?;
};

# Represents the Queries record for the operation: getPerNationalIdWithValidityPeriod
public type GetPerNationalIdWithValidityPeriodQueries record {
    # Expand related entities, see [OData Expand](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("*"|"personNav")[] \$expand?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("cardType"|"country"|"createdBy"|"createdDateTime"|"createdOn"|"isPrimary"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"nationalId"|"notes"|"personIdExternal")[] \$select?;
};

public type RelatedCollectionSFOData_PerEmail record {
    SFOData\.PerEmail[] results?;
};

# Represents the Queries record for the operation: listPerNationalIds
public type ListPerNationalIdsQueries record {
    # Skip the first n items, see [OData Paging - Skip](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$skip?;
    # Show only the first n items, see [OData Paging - Top](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$top = 20;
    # Filter items by property values, see [OData Filtering](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$filter?;
    # Search items by search phrases, see [OData Searching](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$search?;
    # Order items by property values, see [OData Sorting](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("cardType"|"cardType desc"|"country"|"country desc"|"createdBy"|"createdBy desc"|"createdDateTime"|"createdDateTime desc"|"createdOn"|"createdOn desc"|"isPrimary"|"isPrimary desc"|"lastModifiedBy"|"lastModifiedBy desc"|"lastModifiedDateTime"|"lastModifiedDateTime desc"|"lastModifiedOn"|"lastModifiedOn desc"|"nationalId"|"nationalId desc"|"notes"|"notes desc"|"operation"|"operation desc"|"personIdExternal"|"personIdExternal desc")[] \$orderby?;
    # Expand related entities, see [OData Expand](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("*"|"personNav")[] \$expand?;
    # Include count of items, see [OData Count](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    boolean \$count?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("cardType"|"country"|"createdBy"|"createdDateTime"|"createdOn"|"isPrimary"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"nationalId"|"notes"|"operation"|"personIdExternal")[] \$select?;
};

public type PerBiographicalInfoLocITA record {
    SFOData\.PerBiographicalInfoLocITA d?;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    http:CredentialsConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

public type Wrapper record {
    CollectionofPerEmergencyContacts d?;
};

public type PerEmail record {
    SFOData\.PerEmail d?;
};

public type RelatedCollectionSFOData_PerEmergencyContacts record {
    SFOData\.PerEmergencyContacts[] results?;
};

public type PerPhone record {
    SFOData\.PerPhone d?;
};

public type CollectionofPerPhone record {
    SFOData\.PerPhone[] results?;
};

public type CollectionofPerPersonal record {
    SFOData\.PerPersonal[] results?;
};

# Represents the Queries record for the operation: getPerSocialAccount
public type GetPerSocialAccountQueries record {
    # Expand related entities, see [OData Expand](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("*"|"personNav")[] \$expand?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("createdBy"|"createdDateTime"|"createdOn"|"domain"|"imId"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"operation"|"personIdExternal"|"url")[] \$select?;
};

public type CollectionofPerPersonRelationship record {
    SFOData\.PerPersonRelationship[] results?;
};

# Represents the Queries record for the operation: getPerBiographicalInfoLocITA
public type GetPerBiographicalInfoLocITAQueries record {
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("country"|"createdBy"|"createdDateTime"|"createdOn"|"customString1"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"operation"|"personIdExternal"|"placeOfBirth"|"regionOfBirth")[] \$select?;
};

# Represents the Queries record for the operation: getPerBiographicalInfoLocCHL
public type GetPerBiographicalInfoLocCHLQueries record {
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("country"|"createdBy"|"createdDateTime"|"createdOn"|"customString1"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"operation"|"personIdExternal"|"placeOfBirth"|"regionOfBirth")[] \$select?;
};

# Represents the Queries record for the operation: listHrisEmergencyContactAddressDEFLTs
public type ListHrisEmergencyContactAddressDEFLTsQueries record {
    # Skip the first n items, see [OData Paging - Skip](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$skip?;
    # Show only the first n items, see [OData Paging - Top](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$top = 20;
    # Filter items by property values, see [OData Filtering](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$filter?;
    # Search items by search phrases, see [OData Searching](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$search?;
    # Order items by property values, see [OData Sorting](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("address1"|"address1 desc"|"address2"|"address2 desc"|"address3"|"address3 desc"|"address4"|"address4 desc"|"address5"|"address5 desc"|"addressId"|"addressId desc"|"addressType"|"addressType desc"|"city"|"city desc"|"country"|"country desc"|"county"|"county desc"|"createdBy"|"createdBy desc"|"createdDateTime"|"createdDateTime desc"|"createdOn"|"createdOn desc"|"endDate"|"endDate desc"|"lastModifiedBy"|"lastModifiedBy desc"|"lastModifiedDateTime"|"lastModifiedDateTime desc"|"lastModifiedOn"|"lastModifiedOn desc"|"notes"|"notes desc"|"province"|"province desc"|"startDate"|"startDate desc"|"state"|"state desc"|"zipCode"|"zipCode desc")[] \$orderby?;
    # Include count of items, see [OData Count](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    boolean \$count?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("address1"|"address2"|"address3"|"address4"|"address5"|"addressId"|"addressType"|"city"|"country"|"county"|"createdBy"|"createdDateTime"|"createdOn"|"endDate"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"notes"|"province"|"startDate"|"state"|"zipCode")[] \$select?;
};

public type SFOData\.PerNationalIdWithValidityPeriod record {
    string recordId?;
    string validFrom?;
    string validTo?;
    string cardType?;
    string country?;
    string personIdExternal?;
    SFOData\.PerPerson personNav?;
};

public type RelatedCollectionSFOData_PerPhone record {
    SFOData\.PerPhone[] results?;
};

public type Wrapper_17 record {
    CollectionofPerBiographicalInfoLocITA d?;
};

# Represents the Queries record for the operation: listNameElementGOs
public type ListNameElementGOsQueries record {
    # Skip the first n items, see [OData Paging - Skip](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$skip?;
    # Show only the first n items, see [OData Paging - Top](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$top = 20;
    # Filter items by property values, see [OData Filtering](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$filter?;
    # Search items by search phrases, see [OData Searching](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$search?;
    # Order items by property values, see [OData Sorting](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("NameFormatGO_externalCode"|"NameFormatGO_externalCode desc"|"createdBy"|"createdBy desc"|"createdDate"|"createdDate desc"|"createdDateTime"|"createdDateTime desc"|"externalCode"|"externalCode desc"|"lastModifiedBy"|"lastModifiedBy desc"|"lastModifiedDate"|"lastModifiedDate desc"|"lastModifiedDateTime"|"lastModifiedDateTime desc"|"lastModifiedDateWithTZ"|"lastModifiedDateWithTZ desc"|"mdfSystemEffectiveEndDate"|"mdfSystemEffectiveEndDate desc"|"mdfSystemEffectiveStartDate"|"mdfSystemEffectiveStartDate desc"|"mdfSystemEntityId"|"mdfSystemEntityId desc"|"mdfSystemObjectType"|"mdfSystemObjectType desc"|"mdfSystemRecordId"|"mdfSystemRecordId desc"|"mdfSystemRecordStatus"|"mdfSystemRecordStatus desc"|"mdfSystemStatus"|"mdfSystemStatus desc"|"mdfSystemTransactionSequence"|"mdfSystemTransactionSequence desc"|"mdfSystemVersionId"|"mdfSystemVersionId desc"|"nameArtifactEnum"|"nameArtifactEnum desc"|"sampleData"|"sampleData desc"|"separator"|"separator desc")[] \$orderby?;
    # Include count of items, see [OData Count](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    boolean \$count?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("NameFormatGO_externalCode"|"createdBy"|"createdDate"|"createdDateTime"|"externalCode"|"lastModifiedBy"|"lastModifiedDate"|"lastModifiedDateTime"|"lastModifiedDateWithTZ"|"mdfSystemEffectiveEndDate"|"mdfSystemEffectiveStartDate"|"mdfSystemEntityId"|"mdfSystemObjectType"|"mdfSystemRecordId"|"mdfSystemRecordStatus"|"mdfSystemStatus"|"mdfSystemTransactionSequence"|"mdfSystemVersionId"|"nameArtifactEnum"|"sampleData"|"separator")[] \$select?;
};

public type Wrapper_18 record {
    CollectionofPerBiographicalInfoLocVEN d?;
};

public type Wrapper_15 record {
    CollectionofPerBiographicalInfoLocCHL d?;
};

public type Wrapper_16 record {
    CollectionofPerBiographicalInfoLocFRA d?;
};

public type Wrapper_13 record {
    CollectionofNameElementGO d?;
};

public type Wrapper_14 record {
    CollectionofPerBiographicalInfoLocBRA d?;
};

public type Wrapper_11 record {
    CollectionofPerAddressDEFLT d?;
};

public type PerAddressDEFLT record {
    SFOData\.PerAddressDEFLT d?;
};

public type SFOData\.PerBiographicalInfoLocCHL record {
    string country?;
    string personIdExternal?;
};

public type Wrapper_12 record {
    CollectionofNameFormatGO d?;
};

public type SFOData\.PerAddressDEFLT record {
    string addressType?;
    string personIdExternal?;
    string startDate?;
    SFOData\.PerPerson personNav?;
};

public type Wrapper_10 record {
    CollectionofPerNationalIdWithValidityPeriod d?;
};

# Represents the Queries record for the operation: getPerBiographicalInfoLocVEN
public type GetPerBiographicalInfoLocVENQueries record {
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("country"|"createdBy"|"createdDateTime"|"createdOn"|"customString1"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"operation"|"personIdExternal"|"placeOfBirth"|"regionOfBirth")[] \$select?;
};

# Represents the Queries record for the operation: listPerPhones
public type ListPerPhonesQueries record {
    # Skip the first n items, see [OData Paging - Skip](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$skip?;
    # Show only the first n items, see [OData Paging - Top](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$top = 20;
    # Filter items by property values, see [OData Filtering](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$filter?;
    # Search items by search phrases, see [OData Searching](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$search?;
    # Order items by property values, see [OData Sorting](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("areaCode"|"areaCode desc"|"countryCode"|"countryCode desc"|"createdBy"|"createdBy desc"|"createdDateTime"|"createdDateTime desc"|"createdOn"|"createdOn desc"|"extension"|"extension desc"|"includeAllRecords"|"includeAllRecords desc"|"isPrimary"|"isPrimary desc"|"lastModifiedBy"|"lastModifiedBy desc"|"lastModifiedDateTime"|"lastModifiedDateTime desc"|"lastModifiedOn"|"lastModifiedOn desc"|"operation"|"operation desc"|"personIdExternal"|"personIdExternal desc"|"phoneNumber"|"phoneNumber desc"|"phoneType"|"phoneType desc")[] \$orderby?;
    # Expand related entities, see [OData Expand](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("*"|"personNav")[] \$expand?;
    # Include count of items, see [OData Count](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    boolean \$count?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("areaCode"|"countryCode"|"createdBy"|"createdDateTime"|"createdOn"|"extension"|"includeAllRecords"|"isPrimary"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"operation"|"personIdExternal"|"phoneNumber"|"phoneType")[] \$select?;
};

public type CollectionofPerBiographicalInfoLocCHL record {
    SFOData\.PerBiographicalInfoLocCHL[] results?;
};

# Represents the Queries record for the operation: getHrisEmergencyContactAddressDEFLT
public type GetHrisEmergencyContactAddressDEFLTQueries record {
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("address1"|"address2"|"address3"|"address4"|"address5"|"addressId"|"addressType"|"city"|"country"|"county"|"createdBy"|"createdDateTime"|"createdOn"|"endDate"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"notes"|"province"|"startDate"|"state"|"zipCode")[] \$select?;
};

public type PerPersonRelationship record {
    SFOData\.PerPersonRelationship d?;
};

public type CollectionofNameFormatGO record {
    SFOData\.NameFormatGO[] results?;
};

# Represents the Queries record for the operation: getPerAddressDEFLT
public type GetPerAddressDEFLTQueries record {
    # Expand related entities, see [OData Expand](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("*"|"personNav")[] \$expand?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("address1"|"address2"|"address3"|"address4"|"address5"|"addressType"|"city"|"country"|"county"|"createdBy"|"createdDateTime"|"createdOn"|"empUsersSysId"|"endDate"|"includeAllRecords"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"notes"|"operation"|"personIdExternal"|"province"|"startDate"|"state"|"zipCode")[] \$select?;
};

# Represents the Queries record for the operation: listPerSocialAccounts
public type ListPerSocialAccountsQueries record {
    # Skip the first n items, see [OData Paging - Skip](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$skip?;
    # Show only the first n items, see [OData Paging - Top](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$top = 20;
    # Filter items by property values, see [OData Filtering](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$filter?;
    # Search items by search phrases, see [OData Searching](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$search?;
    # Order items by property values, see [OData Sorting](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("createdBy"|"createdBy desc"|"createdDateTime"|"createdDateTime desc"|"createdOn"|"createdOn desc"|"domain"|"domain desc"|"imId"|"imId desc"|"lastModifiedBy"|"lastModifiedBy desc"|"lastModifiedDateTime"|"lastModifiedDateTime desc"|"lastModifiedOn"|"lastModifiedOn desc"|"operation"|"operation desc"|"personIdExternal"|"personIdExternal desc"|"url"|"url desc")[] \$orderby?;
    # Expand related entities, see [OData Expand](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("*"|"personNav")[] \$expand?;
    # Include count of items, see [OData Count](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    boolean \$count?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("createdBy"|"createdDateTime"|"createdOn"|"domain"|"imId"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"operation"|"personIdExternal"|"url")[] \$select?;
};

# Represents the Queries record for the operation: getPerEmergencyContacts
public type GetPerEmergencyContactsQueries record {
    # Expand related entities, see [OData Expand](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("*"|"addressNavDEFLT"|"personNav")[] \$expand?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("addressAddress1"|"addressAddress2"|"addressAddress3"|"addressCity"|"addressCountry"|"addressCounty"|"addressProvince"|"addressState"|"addressZipCode"|"createdBy"|"createdDateTime"|"createdOn"|"email"|"isAddSameAsEmployee"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"name"|"operation"|"personIdExternal"|"phone"|"primaryFlag"|"relationship"|"secondPhone")[] \$select?;
};

public type SFOData\.PerSocialAccount record {
    string domain?;
    string personIdExternal?;
    SFOData\.PerPerson personNav?;
};

public type Wrapper_8 record {
    CollectionofHrisEmergencyContactAddressDEFLT d?;
};

public type Wrapper_9 record {
    CollectionofPerNationalId d?;
};

public type PerEmergencyContacts record {
    SFOData\.PerEmergencyContacts d?;
};

public type Wrapper_4 record {
    CollectionofPerSocialAccount d?;
};

# Represents the Queries record for the operation: listPerBiographicalInfoLocITAs
public type ListPerBiographicalInfoLocITAsQueries record {
    # Skip the first n items, see [OData Paging - Skip](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$skip?;
    # Show only the first n items, see [OData Paging - Top](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$top = 20;
    # Filter items by property values, see [OData Filtering](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$filter?;
    # Search items by search phrases, see [OData Searching](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$search?;
    # Order items by property values, see [OData Sorting](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("country"|"country desc"|"createdBy"|"createdBy desc"|"createdDateTime"|"createdDateTime desc"|"createdOn"|"createdOn desc"|"customString1"|"customString1 desc"|"lastModifiedBy"|"lastModifiedBy desc"|"lastModifiedDateTime"|"lastModifiedDateTime desc"|"lastModifiedOn"|"lastModifiedOn desc"|"operation"|"operation desc"|"personIdExternal"|"personIdExternal desc"|"placeOfBirth"|"placeOfBirth desc"|"regionOfBirth"|"regionOfBirth desc")[] \$orderby?;
    # Include count of items, see [OData Count](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    boolean \$count?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("country"|"createdBy"|"createdDateTime"|"createdOn"|"customString1"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"operation"|"personIdExternal"|"placeOfBirth"|"regionOfBirth")[] \$select?;
};

public type Wrapper_5 record {
    CollectionofPerPerson d?;
};

# Represents the Queries record for the operation: listPersonKeys
public type ListPersonKeysQueries record {
    # Skip the first n items, see [OData Paging - Skip](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$skip?;
    # Show only the first n items, see [OData Paging - Top](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$top = 20;
    # Filter items by property values, see [OData Filtering](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$filter?;
    # Search items by search phrases, see [OData Searching](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$search?;
    # Order items by property values, see [OData Sorting](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("perPersonUuid"|"perPersonUuid desc"|"personId"|"personId desc"|"personIdExternal"|"personIdExternal desc")[] \$orderby?;
    # Include count of items, see [OData Count](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    boolean \$count?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("perPersonUuid"|"personId"|"personIdExternal")[] \$select?;
};

public type Wrapper_6 record {
    CollectionofPerPersonRelationship d?;
};

# Represents the Queries record for the operation: listPerEmergencyContactss
public type ListPerEmergencyContactssQueries record {
    # Skip the first n items, see [OData Paging - Skip](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$skip?;
    # Show only the first n items, see [OData Paging - Top](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$top = 20;
    # Filter items by property values, see [OData Filtering](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$filter?;
    # Search items by search phrases, see [OData Searching](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$search?;
    # Order items by property values, see [OData Sorting](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("addressAddress1"|"addressAddress1 desc"|"addressAddress2"|"addressAddress2 desc"|"addressAddress3"|"addressAddress3 desc"|"addressCity"|"addressCity desc"|"addressCountry"|"addressCountry desc"|"addressCounty"|"addressCounty desc"|"addressProvince"|"addressProvince desc"|"addressState"|"addressState desc"|"addressZipCode"|"addressZipCode desc"|"createdBy"|"createdBy desc"|"createdDateTime"|"createdDateTime desc"|"createdOn"|"createdOn desc"|"email"|"email desc"|"isAddSameAsEmployee"|"isAddSameAsEmployee desc"|"lastModifiedBy"|"lastModifiedBy desc"|"lastModifiedDateTime"|"lastModifiedDateTime desc"|"lastModifiedOn"|"lastModifiedOn desc"|"name"|"name desc"|"operation"|"operation desc"|"personIdExternal"|"personIdExternal desc"|"phone"|"phone desc"|"primaryFlag"|"primaryFlag desc"|"relationship"|"relationship desc"|"secondPhone"|"secondPhone desc")[] \$orderby?;
    # Expand related entities, see [OData Expand](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("*"|"addressNavDEFLT"|"personNav")[] \$expand?;
    # Include count of items, see [OData Count](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    boolean \$count?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("addressAddress1"|"addressAddress2"|"addressAddress3"|"addressCity"|"addressCountry"|"addressCounty"|"addressProvince"|"addressState"|"addressZipCode"|"createdBy"|"createdDateTime"|"createdOn"|"email"|"isAddSameAsEmployee"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"name"|"operation"|"personIdExternal"|"phone"|"primaryFlag"|"relationship"|"secondPhone")[] \$select?;
};

public type Wrapper_7 record {
    CollectionofPerEmail d?;
};

public type Wrapper_1 record {
    CollectionofPerPhone d?;
};

public type Wrapper_2 record {
    CollectionofPersonKey d?;
};

public type CollectionofHrisEmergencyContactAddressDEFLT record {
    SFOData\.HrisEmergencyContactAddressDEFLT[] results?;
};

public type SFOData\.PerEmail record {
    string emailType?;
    string personIdExternal?;
    SFOData\.PerPerson personNav?;
};

public type Wrapper_3 record {
    CollectionofPerPersonal d?;
};

# Represents the Queries record for the operation: getPerBiographicalInfoLocFRA
public type GetPerBiographicalInfoLocFRAQueries record {
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("country"|"createdBy"|"createdDateTime"|"createdOn"|"customString1"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"operation"|"personIdExternal"|"placeOfBirth"|"regionOfBirth")[] \$select?;
};

public type SFOData\.GenerateNextPersonIDResponse record {
};

# Represents the Queries record for the operation: listPerBiographicalInfoLocCHLs
public type ListPerBiographicalInfoLocCHLsQueries record {
    # Skip the first n items, see [OData Paging - Skip](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$skip?;
    # Show only the first n items, see [OData Paging - Top](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$top = 20;
    # Filter items by property values, see [OData Filtering](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$filter?;
    # Search items by search phrases, see [OData Searching](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$search?;
    # Order items by property values, see [OData Sorting](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("country"|"country desc"|"createdBy"|"createdBy desc"|"createdDateTime"|"createdDateTime desc"|"createdOn"|"createdOn desc"|"customString1"|"customString1 desc"|"lastModifiedBy"|"lastModifiedBy desc"|"lastModifiedDateTime"|"lastModifiedDateTime desc"|"lastModifiedOn"|"lastModifiedOn desc"|"operation"|"operation desc"|"personIdExternal"|"personIdExternal desc"|"placeOfBirth"|"placeOfBirth desc"|"regionOfBirth"|"regionOfBirth desc")[] \$orderby?;
    # Include count of items, see [OData Count](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    boolean \$count?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("country"|"createdBy"|"createdDateTime"|"createdOn"|"customString1"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"operation"|"personIdExternal"|"placeOfBirth"|"regionOfBirth")[] \$select?;
};

# Represents the Queries record for the operation: listPerPersonals
public type ListPerPersonalsQueries record {
    # Skip the first n items, see [OData Paging - Skip](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$skip?;
    # Show only the first n items, see [OData Paging - Top](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$top = 20;
    # Filter items by property values, see [OData Filtering](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$filter?;
    # Search items by search phrases, see [OData Searching](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$search?;
    # Order items by property values, see [OData Sorting](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("attachmentId"|"attachmentId desc"|"businessFirstName"|"businessFirstName desc"|"businessLastName"|"businessLastName desc"|"createdBy"|"createdBy desc"|"createdDateTime"|"createdDateTime desc"|"createdOn"|"createdOn desc"|"displayName"|"displayName desc"|"endDate"|"endDate desc"|"firstName"|"firstName desc"|"gender"|"gender desc"|"includeAllRecords"|"includeAllRecords desc"|"initials"|"initials desc"|"lastModifiedBy"|"lastModifiedBy desc"|"lastModifiedDateTime"|"lastModifiedDateTime desc"|"lastModifiedOn"|"lastModifiedOn desc"|"lastName"|"lastName desc"|"maritalStatus"|"maritalStatus desc"|"middleName"|"middleName desc"|"nationality"|"nationality desc"|"nativePreferredLang"|"nativePreferredLang desc"|"operation"|"operation desc"|"personIdExternal"|"personIdExternal desc"|"preferredName"|"preferredName desc"|"salutation"|"salutation desc"|"script"|"script desc"|"startDate"|"startDate desc"|"title"|"title desc")[] \$orderby?;
    # Expand related entities, see [OData Expand](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("*"|"personNav")[] \$expand?;
    # Include count of items, see [OData Count](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    boolean \$count?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("attachmentId"|"businessFirstName"|"businessLastName"|"createdBy"|"createdDateTime"|"createdOn"|"displayName"|"endDate"|"firstName"|"gender"|"includeAllRecords"|"initials"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"lastName"|"maritalStatus"|"middleName"|"nationality"|"nativePreferredLang"|"operation"|"personIdExternal"|"preferredName"|"salutation"|"script"|"startDate"|"title")[] \$select?;
};

# Represents the Queries record for the operation: listPerPersons
public type ListPerPersonsQueries record {
    # Skip the first n items, see [OData Paging - Skip](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$skip?;
    # Show only the first n items, see [OData Paging - Top](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$top = 20;
    # Filter items by property values, see [OData Filtering](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$filter?;
    # Search items by search phrases, see [OData Searching](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$search?;
    # Order items by property values, see [OData Sorting](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("birthName"|"birthName desc"|"countryOfBirth"|"countryOfBirth desc"|"createdBy"|"createdBy desc"|"createdDateTime"|"createdDateTime desc"|"createdOn"|"createdOn desc"|"dateOfBirth"|"dateOfBirth desc"|"includeAllRecords"|"includeAllRecords desc"|"lastModifiedBy"|"lastModifiedBy desc"|"lastModifiedDateTime"|"lastModifiedDateTime desc"|"lastModifiedOn"|"lastModifiedOn desc"|"perPersonUuid"|"perPersonUuid desc"|"personId"|"personId desc"|"personIdExternal"|"personIdExternal desc"|"regionOfBirth"|"regionOfBirth desc"|"userId"|"userId desc")[] \$orderby?;
    # Expand related entities, see [OData Expand](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("*"|"emailNav"|"emergencyContactNav"|"homeAddressNavDEFLT"|"nationalIdNav"|"personRerlationshipNav"|"personalInfoNav"|"phoneNav"|"socialAccountNav")[] \$expand?;
    # Include count of items, see [OData Count](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    boolean \$count?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("birthName"|"countryOfBirth"|"createdBy"|"createdDateTime"|"createdOn"|"dateOfBirth"|"includeAllRecords"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"perPersonUuid"|"personId"|"personIdExternal"|"regionOfBirth"|"userId")[] \$select?;
};

public type PerPersonal record {
    SFOData\.PerPersonal d?;
};

# Represents the Queries record for the operation: getPerNationalId
public type GetPerNationalIdQueries record {
    # Expand related entities, see [OData Expand](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("*"|"personNav")[] \$expand?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("cardType"|"country"|"createdBy"|"createdDateTime"|"createdOn"|"isPrimary"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"nationalId"|"notes"|"operation"|"personIdExternal")[] \$select?;
};

# Represents the Queries record for the operation: listPerNationalIdWithValidityPeriods
public type ListPerNationalIdWithValidityPeriodsQueries record {
    # Skip the first n items, see [OData Paging - Skip](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$skip?;
    # Show only the first n items, see [OData Paging - Top](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$top = 20;
    # Filter items by property values, see [OData Filtering](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$filter?;
    # Search items by search phrases, see [OData Searching](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$search?;
    # Order items by property values, see [OData Sorting](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("cardType"|"cardType desc"|"country"|"country desc"|"createdBy"|"createdBy desc"|"createdDateTime"|"createdDateTime desc"|"createdOn"|"createdOn desc"|"isPrimary"|"isPrimary desc"|"lastModifiedBy"|"lastModifiedBy desc"|"lastModifiedDateTime"|"lastModifiedDateTime desc"|"lastModifiedOn"|"lastModifiedOn desc"|"nationalId"|"nationalId desc"|"personIdExternal"|"personIdExternal desc")[] \$orderby?;
    # Expand related entities, see [OData Expand](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("*"|"personNav")[] \$expand?;
    # Include count of items, see [OData Count](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    boolean \$count?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("cardType"|"country"|"createdBy"|"createdDateTime"|"createdOn"|"isPrimary"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"nationalId"|"notes"|"personIdExternal")[] \$select?;
};

public type SFOData\.PerPersonal record {
    string personIdExternal?;
    string startDate?;
    SFOData\.PerPerson personNav?;
};

# Represents the Queries record for the operation: getPerPhone
public type GetPerPhoneQueries record {
    # Expand related entities, see [OData Expand](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("*"|"personNav")[] \$expand?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("areaCode"|"countryCode"|"createdBy"|"createdDateTime"|"createdOn"|"extension"|"includeAllRecords"|"isPrimary"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"operation"|"personIdExternal"|"phoneNumber"|"phoneType")[] \$select?;
};

# Represents the Queries record for the operation: getNameFormatGO
public type GetNameFormatGOQueries record {
    # Expand related entities, see [OData Expand](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("*"|"nameElements")[] \$expand?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("createdBy"|"createdDateTime"|"externalCode"|"externalName"|"lastModifiedBy"|"lastModifiedDateTime"|"mdfSystemCreatedBy"|"mdfSystemCreatedDate"|"mdfSystemEffectiveEndDate"|"mdfSystemEffectiveStartDate"|"mdfSystemEntityId"|"mdfSystemLastModifiedBy"|"mdfSystemLastModifiedDate"|"mdfSystemLastModifiedDateWithTZ"|"mdfSystemObjectType"|"mdfSystemRecordId"|"mdfSystemRecordStatus"|"mdfSystemStatus"|"mdfSystemTransactionSequence"|"mdfSystemVersionId"|"sample")[] \$select?;
};

public type SFOData\.PerBiographicalInfoLocFRA record {
    string country?;
    string personIdExternal?;
};

public type SFOData\.PerEmergencyContacts record {
    string name?;
    string personIdExternal?;
    string relationship?;
    SFOData\.HrisEmergencyContactAddressDEFLT addressNavDEFLT?;
    SFOData\.PerPerson personNav?;
};

# Represents the Queries record for the operation: getPerPersonRelationship
public type GetPerPersonRelationshipQueries record {
    # Expand related entities, see [OData Expand](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("*"|"personNav"|"relNationalIdNav"|"relPersonNav"|"relPersonalNav")[] \$expand?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("addressAddress1"|"addressAddress2"|"addressAddress3"|"addressCity"|"addressCountry"|"addressCounty"|"addressProvince"|"addressState"|"addressZipCode"|"attachmentId"|"createdBy"|"createdDateTime"|"createdOn"|"endDate"|"firstName"|"isAccompanyingDependent"|"isAddressSameAsPerson"|"isBeneficiary"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"lastName"|"operation"|"personIdExternal"|"relatedPersonIdExternal"|"relationshipType"|"startDate")[] \$select?;
};

# Represents the Queries record for the operation: listNameFormatGOs
public type ListNameFormatGOsQueries record {
    # Skip the first n items, see [OData Paging - Skip](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$skip?;
    # Show only the first n items, see [OData Paging - Top](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$top = 20;
    # Filter items by property values, see [OData Filtering](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$filter?;
    # Search items by search phrases, see [OData Searching](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$search?;
    # Order items by property values, see [OData Sorting](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("createdBy"|"createdBy desc"|"createdDateTime"|"createdDateTime desc"|"externalCode"|"externalCode desc"|"externalName"|"externalName desc"|"lastModifiedBy"|"lastModifiedBy desc"|"lastModifiedDateTime"|"lastModifiedDateTime desc"|"mdfSystemCreatedBy"|"mdfSystemCreatedBy desc"|"mdfSystemCreatedDate"|"mdfSystemCreatedDate desc"|"mdfSystemEffectiveEndDate"|"mdfSystemEffectiveEndDate desc"|"mdfSystemEffectiveStartDate"|"mdfSystemEffectiveStartDate desc"|"mdfSystemEntityId"|"mdfSystemEntityId desc"|"mdfSystemLastModifiedBy"|"mdfSystemLastModifiedBy desc"|"mdfSystemLastModifiedDate"|"mdfSystemLastModifiedDate desc"|"mdfSystemLastModifiedDateWithTZ"|"mdfSystemLastModifiedDateWithTZ desc"|"mdfSystemObjectType"|"mdfSystemObjectType desc"|"mdfSystemRecordId"|"mdfSystemRecordId desc"|"mdfSystemRecordStatus"|"mdfSystemRecordStatus desc"|"mdfSystemStatus"|"mdfSystemStatus desc"|"mdfSystemTransactionSequence"|"mdfSystemTransactionSequence desc"|"mdfSystemVersionId"|"mdfSystemVersionId desc"|"sample"|"sample desc")[] \$orderby?;
    # Expand related entities, see [OData Expand](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("*"|"nameElements")[] \$expand?;
    # Include count of items, see [OData Count](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    boolean \$count?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("createdBy"|"createdDateTime"|"externalCode"|"externalName"|"lastModifiedBy"|"lastModifiedDateTime"|"mdfSystemCreatedBy"|"mdfSystemCreatedDate"|"mdfSystemEffectiveEndDate"|"mdfSystemEffectiveStartDate"|"mdfSystemEntityId"|"mdfSystemLastModifiedBy"|"mdfSystemLastModifiedDate"|"mdfSystemLastModifiedDateWithTZ"|"mdfSystemObjectType"|"mdfSystemRecordId"|"mdfSystemRecordStatus"|"mdfSystemStatus"|"mdfSystemTransactionSequence"|"mdfSystemVersionId"|"sample")[] \$select?;
};

# Represents the Queries record for the operation: listPerEmails
public type ListPerEmailsQueries record {
    # Skip the first n items, see [OData Paging - Skip](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$skip?;
    # Show only the first n items, see [OData Paging - Top](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$top = 20;
    # Filter items by property values, see [OData Filtering](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$filter?;
    # Search items by search phrases, see [OData Searching](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$search?;
    # Order items by property values, see [OData Sorting](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("createdBy"|"createdBy desc"|"createdDateTime"|"createdDateTime desc"|"createdOn"|"createdOn desc"|"emailAddress"|"emailAddress desc"|"emailType"|"emailType desc"|"includeAllRecords"|"includeAllRecords desc"|"isPrimary"|"isPrimary desc"|"lastModifiedBy"|"lastModifiedBy desc"|"lastModifiedDateTime"|"lastModifiedDateTime desc"|"lastModifiedOn"|"lastModifiedOn desc"|"operation"|"operation desc"|"personIdExternal"|"personIdExternal desc")[] \$orderby?;
    # Expand related entities, see [OData Expand](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("*"|"personNav")[] \$expand?;
    # Include count of items, see [OData Count](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    boolean \$count?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("createdBy"|"createdDateTime"|"createdOn"|"emailAddress"|"emailType"|"includeAllRecords"|"isPrimary"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"operation"|"personIdExternal")[] \$select?;
};

public type Result record {
    SFOData\.GenerateNextPersonIDResponse d?;
};

public type CollectionofPerBiographicalInfoLocFRA record {
    SFOData\.PerBiographicalInfoLocFRA[] results?;
};

public type CollectionofPerBiographicalInfoLocBRA record {
    SFOData\.PerBiographicalInfoLocBRA[] results?;
};

# Represents the Queries record for the operation: listPerBiographicalInfoLocVENs
public type ListPerBiographicalInfoLocVENsQueries record {
    # Skip the first n items, see [OData Paging - Skip](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$skip?;
    # Show only the first n items, see [OData Paging - Top](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$top = 20;
    # Filter items by property values, see [OData Filtering](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$filter?;
    # Search items by search phrases, see [OData Searching](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$search?;
    # Order items by property values, see [OData Sorting](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("country"|"country desc"|"createdBy"|"createdBy desc"|"createdDateTime"|"createdDateTime desc"|"createdOn"|"createdOn desc"|"customString1"|"customString1 desc"|"lastModifiedBy"|"lastModifiedBy desc"|"lastModifiedDateTime"|"lastModifiedDateTime desc"|"lastModifiedOn"|"lastModifiedOn desc"|"operation"|"operation desc"|"personIdExternal"|"personIdExternal desc"|"placeOfBirth"|"placeOfBirth desc"|"regionOfBirth"|"regionOfBirth desc")[] \$orderby?;
    # Include count of items, see [OData Count](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    boolean \$count?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("country"|"createdBy"|"createdDateTime"|"createdOn"|"customString1"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"operation"|"personIdExternal"|"placeOfBirth"|"regionOfBirth")[] \$select?;
};

public type PerBiographicalInfoLocBRA record {
    SFOData\.PerBiographicalInfoLocBRA d?;
};

public type SFOData\.PerPerson record {
    string personIdExternal?;
    RelatedCollectionSFOData_PerEmail emailNav?;
    RelatedCollectionSFOData_PerEmergencyContacts emergencyContactNav?;
    RelatedCollectionSFOData_PerAddressDEFLT homeAddressNavDEFLT?;
    RelatedCollectionSFOData_PerNationalId nationalIdNav?;
    RelatedCollectionSFOData_PerPersonRelationship personRerlationshipNav?;
    RelatedCollectionSFOData_PerPersonal personalInfoNav?;
    RelatedCollectionSFOData_PerPhone phoneNav?;
    RelatedCollectionSFOData_PerSocialAccount socialAccountNav?;
};

public type SFOData\.PerBiographicalInfoLocBRA record {
    string country?;
    string personIdExternal?;
};

public type PerBiographicalInfoLocFRA record {
    SFOData\.PerBiographicalInfoLocFRA d?;
};

public type RelatedCollectionSFOData_PerPersonRelationship record {
    SFOData\.PerPersonRelationship[] results?;
};

# Represents the Queries record for the operation: getPersonKey
public type GetPersonKeyQueries record {
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("perPersonUuid"|"personId"|"personIdExternal")[] \$select?;
};

public type CollectionofPersonKey record {
    SFOData\.PersonKey[] results?;
};

public type CollectionofPerNationalIdWithValidityPeriod record {
    SFOData\.PerNationalIdWithValidityPeriod[] results?;
};

# Represents the Queries record for the operation: listPerAddressDEFLTs
public type ListPerAddressDEFLTsQueries record {
    # Skip the first n items, see [OData Paging - Skip](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$skip?;
    # Show only the first n items, see [OData Paging - Top](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$top = 20;
    # Filter items by property values, see [OData Filtering](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$filter?;
    # Search items by search phrases, see [OData Searching](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$search?;
    # Order items by property values, see [OData Sorting](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("address1"|"address1 desc"|"address2"|"address2 desc"|"address3"|"address3 desc"|"address4"|"address4 desc"|"address5"|"address5 desc"|"addressType"|"addressType desc"|"city"|"city desc"|"country"|"country desc"|"county"|"county desc"|"createdBy"|"createdBy desc"|"createdDateTime"|"createdDateTime desc"|"createdOn"|"createdOn desc"|"empUsersSysId"|"empUsersSysId desc"|"endDate"|"endDate desc"|"includeAllRecords"|"includeAllRecords desc"|"lastModifiedBy"|"lastModifiedBy desc"|"lastModifiedDateTime"|"lastModifiedDateTime desc"|"lastModifiedOn"|"lastModifiedOn desc"|"notes"|"notes desc"|"operation"|"operation desc"|"personIdExternal"|"personIdExternal desc"|"province"|"province desc"|"startDate"|"startDate desc"|"state"|"state desc"|"zipCode"|"zipCode desc")[] \$orderby?;
    # Expand related entities, see [OData Expand](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("*"|"personNav")[] \$expand?;
    # Include count of items, see [OData Count](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    boolean \$count?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("address1"|"address2"|"address3"|"address4"|"address5"|"addressType"|"city"|"country"|"county"|"createdBy"|"createdDateTime"|"createdOn"|"empUsersSysId"|"endDate"|"includeAllRecords"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"notes"|"operation"|"personIdExternal"|"province"|"startDate"|"state"|"zipCode")[] \$select?;
};

public type PerNationalIdWithValidityPeriod record {
    SFOData\.PerNationalIdWithValidityPeriod d?;
};

public type CollectionofPerEmail record {
    SFOData\.PerEmail[] results?;
};

# Represents the Queries record for the operation: getPerEmail
public type GetPerEmailQueries record {
    # Expand related entities, see [OData Expand](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("*"|"personNav")[] \$expand?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("createdBy"|"createdDateTime"|"createdOn"|"emailAddress"|"emailType"|"includeAllRecords"|"isPrimary"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"operation"|"personIdExternal")[] \$select?;
};

public type SFOData\.PerNationalId record {
    string cardType?;
    string country?;
    string personIdExternal?;
    SFOData\.PerPerson personNav?;
};

public type SFOData\.NameElementGO record {
    string NameFormatGO_externalCode?;
    string externalCode?;
};

public type PerPerson record {
    SFOData\.PerPerson d?;
};

# Represents the Queries record for the operation: getNameElementGO
public type GetNameElementGOQueries record {
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("NameFormatGO_externalCode"|"createdBy"|"createdDate"|"createdDateTime"|"externalCode"|"lastModifiedBy"|"lastModifiedDate"|"lastModifiedDateTime"|"lastModifiedDateWithTZ"|"mdfSystemEffectiveEndDate"|"mdfSystemEffectiveStartDate"|"mdfSystemEntityId"|"mdfSystemObjectType"|"mdfSystemRecordId"|"mdfSystemRecordStatus"|"mdfSystemStatus"|"mdfSystemTransactionSequence"|"mdfSystemVersionId"|"nameArtifactEnum"|"sampleData"|"separator")[] \$select?;
};

public type SFOData\.PersonKey record {
    string personIdExternal?;
};

public type NameFormatGO record {
    SFOData\.NameFormatGO d?;
};

public type SFOData\.PerPersonRelationship record {
    string personIdExternal?;
    string relatedPersonIdExternal?;
    string startDate?;
    SFOData\.PerPerson personNav?;
    SFOData\.PerNationalId relNationalIdNav?;
    SFOData\.PerPerson relPersonNav?;
    SFOData\.PerPersonal relPersonalNav?;
};

# Represents the Queries record for the operation: getPerPerson
public type GetPerPersonQueries record {
    # Expand related entities, see [OData Expand](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("*"|"emailNav"|"emergencyContactNav"|"homeAddressNavDEFLT"|"nationalIdNav"|"personRerlationshipNav"|"personalInfoNav"|"phoneNav"|"socialAccountNav")[] \$expand?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("birthName"|"countryOfBirth"|"createdBy"|"createdDateTime"|"createdOn"|"dateOfBirth"|"includeAllRecords"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"perPersonUuid"|"personId"|"personIdExternal"|"regionOfBirth"|"userId")[] \$select?;
};

public type CollectionofPerAddressDEFLT record {
    SFOData\.PerAddressDEFLT[] results?;
};

public type SFOData\.NameFormatGO record {
    string externalCode?;
    RelatedCollectionSFOData_NameElementGO nameElements?;
};

public type RelatedCollectionSFOData_PerPersonal record {
    SFOData\.PerPersonal[] results?;
};

# Represents the Queries record for the operation: getPerPersonal
public type GetPerPersonalQueries record {
    # Expand related entities, see [OData Expand](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("*"|"personNav")[] \$expand?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("attachmentId"|"businessFirstName"|"businessLastName"|"createdBy"|"createdDateTime"|"createdOn"|"displayName"|"endDate"|"firstName"|"gender"|"includeAllRecords"|"initials"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"lastName"|"maritalStatus"|"middleName"|"nationality"|"nativePreferredLang"|"operation"|"personIdExternal"|"preferredName"|"salutation"|"script"|"startDate"|"title")[] \$select?;
};

# Represents the Queries record for the operation: getPerBiographicalInfoLocBRA
public type GetPerBiographicalInfoLocBRAQueries record {
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("country"|"createdBy"|"createdDateTime"|"createdOn"|"customString1"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"operation"|"personIdExternal"|"placeOfBirth"|"regionOfBirth")[] \$select?;
};

public type SFOData\.HrisEmergencyContactAddressDEFLT record {
    string addressId?;
};

public type PersonKey record {
    SFOData\.PersonKey d?;
};

public type NameElementGO record {
    SFOData\.NameElementGO d?;
};

public type RelatedCollectionSFOData_PerNationalId record {
    SFOData\.PerNationalId[] results?;
};

public type RelatedCollectionSFOData_PerAddressDEFLT record {
    SFOData\.PerAddressDEFLT[] results?;
};

public type CollectionofPerEmergencyContacts record {
    SFOData\.PerEmergencyContacts[] results?;
};

public type CollectionofPerNationalId record {
    SFOData\.PerNationalId[] results?;
};

public type CollectionofPerSocialAccount record {
    SFOData\.PerSocialAccount[] results?;
};

public type CollectionofPerPerson record {
    SFOData\.PerPerson[] results?;
};

# Represents the Queries record for the operation: listPerPersonRelationships
public type ListPerPersonRelationshipsQueries record {
    # Skip the first n items, see [OData Paging - Skip](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$skip?;
    # Show only the first n items, see [OData Paging - Top](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$top = 20;
    # Filter items by property values, see [OData Filtering](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$filter?;
    # Search items by search phrases, see [OData Searching](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$search?;
    # Order items by property values, see [OData Sorting](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("addressAddress1"|"addressAddress1 desc"|"addressAddress2"|"addressAddress2 desc"|"addressAddress3"|"addressAddress3 desc"|"addressCity"|"addressCity desc"|"addressCountry"|"addressCountry desc"|"addressCounty"|"addressCounty desc"|"addressProvince"|"addressProvince desc"|"addressState"|"addressState desc"|"addressZipCode"|"addressZipCode desc"|"attachmentId"|"attachmentId desc"|"createdBy"|"createdBy desc"|"createdDateTime"|"createdDateTime desc"|"createdOn"|"createdOn desc"|"endDate"|"endDate desc"|"firstName"|"firstName desc"|"isAccompanyingDependent"|"isAccompanyingDependent desc"|"isAddressSameAsPerson"|"isAddressSameAsPerson desc"|"isBeneficiary"|"isBeneficiary desc"|"lastModifiedBy"|"lastModifiedBy desc"|"lastModifiedDateTime"|"lastModifiedDateTime desc"|"lastModifiedOn"|"lastModifiedOn desc"|"lastName"|"lastName desc"|"operation"|"operation desc"|"personIdExternal"|"personIdExternal desc"|"relatedPersonIdExternal"|"relatedPersonIdExternal desc"|"relationshipType"|"relationshipType desc"|"startDate"|"startDate desc")[] \$orderby?;
    # Expand related entities, see [OData Expand](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("*"|"personNav"|"relNationalIdNav"|"relPersonNav"|"relPersonalNav")[] \$expand?;
    # Include count of items, see [OData Count](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    boolean \$count?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("addressAddress1"|"addressAddress2"|"addressAddress3"|"addressCity"|"addressCountry"|"addressCounty"|"addressProvince"|"addressState"|"addressZipCode"|"attachmentId"|"createdBy"|"createdDateTime"|"createdOn"|"endDate"|"firstName"|"isAccompanyingDependent"|"isAddressSameAsPerson"|"isBeneficiary"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"lastName"|"operation"|"personIdExternal"|"relatedPersonIdExternal"|"relationshipType"|"startDate")[] \$select?;
};

public type RelatedCollectionSFOData_PerSocialAccount record {
    SFOData\.PerSocialAccount[] results?;
};

public type PerSocialAccount record {
    SFOData\.PerSocialAccount d?;
};

# Represents the Queries record for the operation: listPerBiographicalInfoLocBRAs
public type ListPerBiographicalInfoLocBRAsQueries record {
    # Skip the first n items, see [OData Paging - Skip](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$skip?;
    # Show only the first n items, see [OData Paging - Top](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$top = 20;
    # Filter items by property values, see [OData Filtering](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$filter?;
    # Search items by search phrases, see [OData Searching](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$search?;
    # Order items by property values, see [OData Sorting](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("country"|"country desc"|"createdBy"|"createdBy desc"|"createdDateTime"|"createdDateTime desc"|"createdOn"|"createdOn desc"|"customString1"|"customString1 desc"|"lastModifiedBy"|"lastModifiedBy desc"|"lastModifiedDateTime"|"lastModifiedDateTime desc"|"lastModifiedOn"|"lastModifiedOn desc"|"operation"|"operation desc"|"personIdExternal"|"personIdExternal desc"|"placeOfBirth"|"placeOfBirth desc"|"regionOfBirth"|"regionOfBirth desc")[] \$orderby?;
    # Include count of items, see [OData Count](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    boolean \$count?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("country"|"createdBy"|"createdDateTime"|"createdOn"|"customString1"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"operation"|"personIdExternal"|"placeOfBirth"|"regionOfBirth")[] \$select?;
};