// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.org).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/constraint;
import ballerina/http;

# Represents the Queries record for the operation: listEmployeeDismissalProtectionDetails
public type ListEmployeeDismissalProtectionDetailsQueries record {
    # Skip the first n items, see [OData Paging - Skip](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374631)
    int \$skip?;
    # Show only the first n items, see [OData Paging - Top](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374630)
    int \$top = 5;
    # Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374625)
    string \$filter?;
    # Search items by search phrases, see [OData Searching](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374633)
    string \$search?;
    # Order items by property values, see [OData Sorting](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374629)
    ("EmployeeDismissalProtection_workerId"|"EmployeeDismissalProtection_workerId desc"|"createdBy"|"createdBy desc"|"createdDateTime"|"createdDateTime desc"|"dismissalProtectionType"|"dismissalProtectionType desc"|"externalCode"|"externalCode desc"|"lastModifiedBy"|"lastModifiedBy desc"|"lastModifiedDateTime"|"lastModifiedDateTime desc"|"mdfSystemRecordStatus"|"mdfSystemRecordStatus desc"|"protectionEndDate"|"protectionEndDate desc"|"protectionStartDate"|"protectionStartDate desc")[] \$orderby?;
    # Include count of items, see [OData Count](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374632)
    boolean \$count?;
    # Select properties to be returned, see [OData Select](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374620)
    ("EmployeeDismissalProtection_workerId"|"createdBy"|"createdDateTime"|"dismissalProtectionType"|"externalCode"|"lastModifiedBy"|"lastModifiedDateTime"|"mdfSystemRecordStatus"|"protectionEndDate"|"protectionStartDate")[] \$select?;
};

public type Wrapper record {
    CollectionofEmployeeDismissalProtectionDetail d?;
};

# Represents the Queries record for the operation: listEmployeeDismissalProtections
public type ListEmployeeDismissalProtectionsQueries record {
    # Skip the first n items, see [OData Paging - Skip](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374631)
    int \$skip?;
    # Show only the first n items, see [OData Paging - Top](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374630)
    int \$top = 5;
    # Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374625)
    string \$filter?;
    # Search items by search phrases, see [OData Searching](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374633)
    string \$search?;
    # Order items by property values, see [OData Sorting](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374629)
    ("createdBy"|"createdBy desc"|"createdDateTime"|"createdDateTime desc"|"lastModifiedBy"|"lastModifiedBy desc"|"lastModifiedDateTime"|"lastModifiedDateTime desc"|"mdfSystemRecordStatus"|"mdfSystemRecordStatus desc"|"workerId"|"workerId desc")[] \$orderby?;
    # Expand related entities, see [OData Expand](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374621)
    ("*"|"empDismissalProtectionDetails")[] \$expand?;
    # Include count of items, see [OData Count](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374632)
    boolean \$count?;
    # Select properties to be returned, see [OData Select](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374620)
    ("createdBy"|"createdDateTime"|"lastModifiedBy"|"lastModifiedDateTime"|"mdfSystemRecordStatus"|"workerId")[] \$select?;
};

public type RelatedCollectionSFOData_EmployeeDismissalProtectionDetail record {
    EmployeeDismissalProtectionDetail[] results?;
};

public type EmployeeDismissalProtection record {
    @constraint:String {maxLength: 100}
    string workerId?;
    RelatedCollectionSFOData_EmployeeDismissalProtectionDetail empDismissalProtectionDetails?;
};

public type EmployeeDismissalProtection_1 record {
    EmployeeDismissalProtection d?;
};

# Represents the Headers record for the operation: deleteEmployeeDismissalProtection
public type DeleteEmployeeDismissalProtectionHeaders record {
    # ETag
    string If\-Match?;
};

public type ModifiedEmployeeDismissalProtectionDetail record {
    EmployeeDismissalProtectionDetail d?;
};

public type EmployeeDismissalProtectionDetail record {
    @constraint:String {maxLength: 100}
    string EmployeeDismissalProtection_workerId?;
    @constraint:String {maxLength: 128}
    string externalCode?;
};

public type CollectionofEmployeeDismissalProtection record {
    EmployeeDismissalProtection[] results?;
};

public type ModifiedEmployeeDismissalProtection record {
    EmployeeDismissalProtection d?;
};

public type CreatedEmployeeDismissalProtection record {
    EmployeeDismissalProtection d?;
};

public type CreatedEmployeeDismissalProtectionDetail record {
    EmployeeDismissalProtectionDetail d?;
};

public type EmployeeDismissalProtectionDetail_1 record {
    EmployeeDismissalProtectionDetail d?;
};

# Represents the Headers record for the operation: deleteEmployeeDismissalProtectionDetail
public type DeleteEmployeeDismissalProtectionDetailHeaders record {
    # ETag
    string If\-Match?;
};

public type CollectionofEmployeeDismissalProtectionDetail record {
    EmployeeDismissalProtectionDetail[] results?;
};

public type Wrapper_1 record {
    CollectionofEmployeeDismissalProtection d?;
};

# Represents the Queries record for the operation: getEmployeeDismissalProtection
public type GetEmployeeDismissalProtectionQueries record {
    # Expand related entities, see [OData Expand](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374621)
    ("*"|"empDismissalProtectionDetails")[] \$expand?;
    # Select properties to be returned, see [OData Select](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374620)
    ("createdBy"|"createdDateTime"|"lastModifiedBy"|"lastModifiedDateTime"|"mdfSystemRecordStatus"|"workerId")[] \$select?;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    http:CredentialsConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

# Represents the Queries record for the operation: getEmployeeDismissalProtectionDetail
public type GetEmployeeDismissalProtectionDetailQueries record {
    # Select properties to be returned, see [OData Select](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374620)
    ("EmployeeDismissalProtection_workerId"|"createdBy"|"createdDateTime"|"dismissalProtectionType"|"externalCode"|"lastModifiedBy"|"lastModifiedDateTime"|"mdfSystemRecordStatus"|"protectionEndDate"|"protectionStartDate")[] \$select?;
};
