org.gradle.caching=true
group=io.ballerina.lib


# SAP SuccessFactors Employee Central Modules
version=0.8.0-SNAPSHOT
ecalternativecostdistributionVersion=0.8.0-SNAPSHOT
ecapprenticemanagementVersion=0.8.0-SNAPSHOT
eccompensationinformationVersion=0.8.0-SNAPSHOT
ecdismissalprotectionVersion=0.8.0-SNAPSHOT
ecemployeeprofileVersion=0.8.0-SNAPSHOT
ecemploymentinformationVersion=0.8.0-SNAPSHOT
ecmasterdatareplicationVersion=0.8.0-SNAPSHOT
ecpayrolltimesheetsVersion=0.8.0-SNAPSHOT
ecpositionmanagementVersion=0.8.0-SNAPSHOT
ecskillsmanagementVersion=0.8.0-SNAPSHOT
ecworkflowVersion=0.8.0-SNAPSHOT
employeecentralecVersion=0.8.0-SNAPSHOT
ecadvancesVersion=0.8.0-SNAPSHOT
ecemployeecentralpayrollVersion=0.8.0-SNAPSHOT
ecfoundationorganizationVersion=0.8.0-SNAPSHOT
ecglobalassignmentVersion=0.8.0-SNAPSHOT
ecglobalbenefitsVersion=0.8.0-SNAPSHOT
ecincometaxdeclarationVersion=0.8.0-SNAPSHOT
ecpaymentinformationVersion=0.8.0-SNAPSHOT
ecpersonalinformationVersion=0.8.0-SNAPSHOT
ectimeoffVersion=0.8.0-SNAPSHOT

ballerinaGradlePluginVersion=2.3.0
downloadPluginVersion=5.4.0
releasePluginVersion=2.8.0

ballerinaLangVersion=2201.13.0
