org.gradle.caching=true
group=io.ballerina.lib


# SAP SuccessFactors Employee Central Modules
version=1.1.2-SNAPSHOT
ecalternativecostdistributionVersion=1.1.1-SNAPSHOT
ecapprenticemanagementVersion=1.1.1-SNAPSHOT
eccompensationinformationVersion=1.1.1-SNAPSHOT
ecdismissalprotectionVersion=1.1.1-SNAPSHOT
ecemployeeprofileVersion=1.1.1-SNAPSHOT
ecemploymentinformationVersion=1.1.1-SNAPSHOT
ecmasterdatareplicationVersion=1.1.1-SNAPSHOT
ecpayrolltimesheetsVersion=1.1.1-SNAPSHOT
ecpositionmanagementVersion=1.1.1-SNAPSHOT
ecskillsmanagementVersion=1.1.1-SNAPSHOT
ecworkflowVersion=1.1.1-SNAPSHOT
employeecentralecVersion=1.1.1-SNAPSHOT
ecadvancesVersion=1.1.1-SNAPSHOT
ecemployeecentralpayrollVersion=1.1.1-SNAPSHOT
ecfoundationorganizationVersion=1.1.2-SNAPSHOT
ecglobalassignmentVersion=1.1.1-SNAPSHOT
ecglobalbenefitsVersion=1.1.1-SNAPSHOT
ecincometaxdeclarationVersion=1.1.1-SNAPSHOT
ecpaymentinformationVersion=1.1.1-SNAPSHOT
ecpersonalinformationVersion=1.1.1-SNAPSHOT
ectimeoffVersion=1.1.1-SNAPSHOT

ballerinaGradlePluginVersion=2.3.0
downloadPluginVersion=5.4.0
releasePluginVersion=2.8.0

ballerinaLangVersion=2201.13.0
