org.gradle.caching=true
group=io.ballerina.lib


# SAP SuccessFactors Employee Central Modules
version=1.1.0
ecalternativecostdistributionVersion=1.1.0
ecapprenticemanagementVersion=1.1.0-SNAPSHOT
eccompensationinformationVersion=1.1.0-SNAPSHOT
ecdismissalprotectionVersion=1.1.0-SNAPSHOT
ecemployeeprofileVersion=1.1.0-SNAPSHOT
ecemploymentinformationVersion=1.1.0-SNAPSHOT
ecmasterdatareplicationVersion=1.1.0-SNAPSHOT
ecpayrolltimesheetsVersion=1.1.0-SNAPSHOT
ecpositionmanagementVersion=1.1.0-SNAPSHOT
ecskillsmanagementVersion=1.1.0-SNAPSHOT
ecworkflowVersion=1.1.0-SNAPSHOT
employeecentralecVersion=1.1.0-SNAPSHOT
ecadvancesVersion=1.1.0-SNAPSHOT
ecemployeecentralpayrollVersion=1.1.0-SNAPSHOT
ecfoundationorganizationVersion=1.1.0-SNAPSHOT
ecglobalassignmentVersion=1.1.0-SNAPSHOT
ecglobalbenefitsVersion=1.1.0-SNAPSHOT
ecincometaxdeclarationVersion=1.1.0-SNAPSHOT
ecpaymentinformationVersion=1.1.0-SNAPSHOT
ecpersonalinformationVersion=1.1.0-SNAPSHOT
ectimeoffVersion=1.1.0-SNAPSHOT

ballerinaGradlePluginVersion=2.3.0
downloadPluginVersion=5.4.0
releasePluginVersion=2.8.0

ballerinaLangVersion=2201.13.0
