// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.org).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;
import ballerinax/sap;

# You can use these APIs to distribute the costs of an employee over multiple alternative cost centers.
#
# You can find your company's API server in [List of API Servers in SAP SuccessFactors.](https://help.sap.com/viewer/d599f15995d348a1b45ba5603e2aba9b/LATEST/en-US/af2b8d5437494b12be88fe374eba75b6.html)
public isolated client class Client {
    final sap:Client clientEp;

    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string hostname, int port = 443) returns error? {
        string serviceUrl = string `https://${hostname}:${port}/successfactors/odata/v2`;
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # Get entities from EmpCostDistribution
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listEmpCostDistributions(map<string|string[]> headers = {}, *ListEmpCostDistributionsQueries queries) returns Wrapper|error {
        string resourcePath = string `/EmpCostDistribution`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Add new entity to EmpCostDistribution
    #
    # + headers - Headers to be sent with the request 
    # + payload - New entity 
    # + return - Created entity 
    remote isolated function createEmpCostDistribution(SFOData\.EmpCostDistribution payload, map<string|string[]> headers = {}) returns CreatedEmpCostDistribution|error {
        string resourcePath = string `/EmpCostDistribution`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get entity from EmpCostDistribution by key
    #
    # + effectiveStartDate - key: effectiveStartDate
    # + usersSysId - key: usersSysId
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getEmpCostDistribution(string effectiveStartDate, string usersSysId, map<string|string[]> headers = {}, *GetEmpCostDistributionQueries queries) returns EmpCostDistribution|error {
        string resourcePath = string `/EmpCostDistribution(effectiveStartDate=${getEncodedUri(effectiveStartDate)},usersSysId='${getEncodedUri(usersSysId)}')`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update entity in EmpCostDistribution
    #
    # + effectiveStartDate - key: effectiveStartDate
    # + usersSysId - key: usersSysId
    # + headers - Headers to be sent with the request 
    # + payload - New property values 
    # + return - Success 
    remote isolated function updateEmpCostDistribution(string effectiveStartDate, string usersSysId, ModifiedEmpCostDistribution payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/EmpCostDistribution(effectiveStartDate=${getEncodedUri(effectiveStartDate)},usersSysId='${getEncodedUri(usersSysId)}')`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # Delete entity from EmpCostDistribution
    #
    # + effectiveStartDate - key: effectiveStartDate
    # + usersSysId - key: usersSysId
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function deleteEmpCostDistribution(string effectiveStartDate, string usersSysId, DeleteEmpCostDistributionHeaders headers = {}) returns error? {
        string resourcePath = string `/EmpCostDistribution(effectiveStartDate=${getEncodedUri(effectiveStartDate)},usersSysId='${getEncodedUri(usersSysId)}')`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Get entities from EmpCostDistributionItem
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entities 
    remote isolated function listEmpCostDistributionItems(map<string|string[]> headers = {}, *ListEmpCostDistributionItemsQueries queries) returns Wrapper_1|error {
        string resourcePath = string `/EmpCostDistributionItem`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Add new entity to EmpCostDistributionItem
    #
    # + headers - Headers to be sent with the request 
    # + payload - New entity 
    # + return - Created entity 
    remote isolated function createEmpCostDistributionItem(SFOData\.EmpCostDistributionItem payload, map<string|string[]> headers = {}) returns CreatedEmpCostDistributionItem|error {
        string resourcePath = string `/EmpCostDistributionItem`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get entity from EmpCostDistributionItem by key
    #
    # + EmpCostDistribution_effectiveStartDate - key: EmpCostDistribution_effectiveStartDate
    # + EmpCostDistribution_usersSysId - key: EmpCostDistribution_usersSysId
    # + externalCode - key: externalCode
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved entity 
    remote isolated function getEmpCostDistributionItem(string EmpCostDistribution_effectiveStartDate, string EmpCostDistribution_usersSysId, int externalCode, map<string|string[]> headers = {}, *GetEmpCostDistributionItemQueries queries) returns EmpCostDistributionItem|error {
        string resourcePath = string `/EmpCostDistributionItem(EmpCostDistribution_effectiveStartDate=${getEncodedUri(EmpCostDistribution_effectiveStartDate)},EmpCostDistribution_usersSysId='${getEncodedUri(EmpCostDistribution_usersSysId)}',externalCode=${getEncodedUri(externalCode)})`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update entity in EmpCostDistributionItem
    #
    # + EmpCostDistribution_effectiveStartDate - key: EmpCostDistribution_effectiveStartDate
    # + EmpCostDistribution_usersSysId - key: EmpCostDistribution_usersSysId
    # + externalCode - key: externalCode
    # + headers - Headers to be sent with the request 
    # + payload - New property values 
    # + return - Success 
    remote isolated function updateEmpCostDistributionItem(string EmpCostDistribution_effectiveStartDate, string EmpCostDistribution_usersSysId, int externalCode, ModifiedEmpCostDistributionItem payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/EmpCostDistributionItem(EmpCostDistribution_effectiveStartDate=${getEncodedUri(EmpCostDistribution_effectiveStartDate)},EmpCostDistribution_usersSysId='${getEncodedUri(EmpCostDistribution_usersSysId)}',externalCode=${getEncodedUri(externalCode)})`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # Delete entity from EmpCostDistributionItem
    #
    # + EmpCostDistribution_effectiveStartDate - key: EmpCostDistribution_effectiveStartDate
    # + EmpCostDistribution_usersSysId - key: EmpCostDistribution_usersSysId
    # + externalCode - key: externalCode
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function deleteEmpCostDistributionItem(string EmpCostDistribution_effectiveStartDate, string EmpCostDistribution_usersSysId, int externalCode, DeleteEmpCostDistributionItemHeaders headers = {}) returns error? {
        string resourcePath = string `/EmpCostDistributionItem(EmpCostDistribution_effectiveStartDate=${getEncodedUri(EmpCostDistribution_effectiveStartDate)},EmpCostDistribution_usersSysId='${getEncodedUri(EmpCostDistribution_usersSysId)}',externalCode=${getEncodedUri(externalCode)})`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }
}
