// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

public type CollectionofSecondaryAssignmentsItem record {
    SecondaryAssignmentsItem[] results?;
};

public type SecondaryAssignmentsItem record {
    SecondaryAssignmentsItem d?;
};

public type ModifiedSecondaryAssignments record {
    SecondaryAssignments d?;
};

public type CollectionofSecondaryAssignments record {
    SecondaryAssignments[] results?;
};

# Represents the Queries record for the operation: listSecondaryAssignmentsItems
public type ListSecondaryAssignmentsItemsQueries record {
    # Skip the first n items, see [OData Paging - Skip](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$skip?;
    # Show only the first n items, see [OData Paging - Top](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$top = 20;
    # Filter items by property values, see [OData Filtering](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$filter?;
    # Search items by search phrases, see [OData Searching](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$search?;
    # Order items by property values, see [OData Sorting](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("SecondaryAssignments_effectiveStartDate"|"SecondaryAssignments_effectiveStartDate desc"|"SecondaryAssignments_externalCode"|"SecondaryAssignments_externalCode desc"|"createdBy"|"createdBy desc"|"createdDate"|"createdDate desc"|"createdDateTime"|"createdDateTime desc"|"externalCode"|"externalCode desc"|"lastModifiedBy"|"lastModifiedBy desc"|"lastModifiedDate"|"lastModifiedDate desc"|"lastModifiedDateTime"|"lastModifiedDateTime desc"|"lastModifiedDateWithTZ"|"lastModifiedDateWithTZ desc"|"mdfSystemEffectiveEndDate"|"mdfSystemEffectiveEndDate desc"|"mdfSystemEffectiveStartDate"|"mdfSystemEffectiveStartDate desc"|"mdfSystemEntityId"|"mdfSystemEntityId desc"|"mdfSystemObjectType"|"mdfSystemObjectType desc"|"mdfSystemRecordId"|"mdfSystemRecordId desc"|"mdfSystemRecordStatus"|"mdfSystemRecordStatus desc"|"mdfSystemStatus"|"mdfSystemStatus desc"|"mdfSystemTransactionSequence"|"mdfSystemTransactionSequence desc"|"mdfSystemVersionId"|"mdfSystemVersionId desc"|"usersSysId"|"usersSysId desc")[] \$orderby?;
    # Include count of items, see [OData Count](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    boolean \$count?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("SecondaryAssignments_effectiveStartDate"|"SecondaryAssignments_externalCode"|"createdBy"|"createdDate"|"createdDateTime"|"externalCode"|"lastModifiedBy"|"lastModifiedDate"|"lastModifiedDateTime"|"lastModifiedDateWithTZ"|"mdfSystemEffectiveEndDate"|"mdfSystemEffectiveStartDate"|"mdfSystemEntityId"|"mdfSystemObjectType"|"mdfSystemRecordId"|"mdfSystemRecordStatus"|"mdfSystemStatus"|"mdfSystemTransactionSequence"|"mdfSystemVersionId"|"usersSysId")[] \$select?;
};

public type RelatedCollectionSFOData_SecondaryAssignmentsItem record {
    SecondaryAssignmentsItem[] results?;
};

public type CreatedSecondaryAssignments record {
    SecondaryAssignments d?;
};

# Represents the Queries record for the operation: listRightToReturns
public type ListRightToReturnsQueries record {
    # Skip the first n items, see [OData Paging - Skip](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$skip?;
    # Show only the first n items, see [OData Paging - Top](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$top = 20;
    # Filter items by property values, see [OData Filtering](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$filter?;
    # Search items by search phrases, see [OData Searching](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$search?;
    # Order items by property values, see [OData Sorting](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("Position_code"|"Position_code desc"|"Position_effectiveStartDate"|"Position_effectiveStartDate desc"|"code"|"code desc"|"createdBy"|"createdBy desc"|"createdDateTime"|"createdDateTime desc"|"gaEndJobInfoId"|"gaEndJobInfoId desc"|"gaEventReason"|"gaEventReason desc"|"gaStartJobInfoId"|"gaStartJobInfoId desc"|"lastModifiedBy"|"lastModifiedBy desc"|"lastModifiedDateTime"|"lastModifiedDateTime desc"|"loaTimeType"|"loaTimeType desc"|"mdfSystemCreatedBy"|"mdfSystemCreatedBy desc"|"mdfSystemCreatedDate"|"mdfSystemCreatedDate desc"|"mdfSystemEffectiveEndDate"|"mdfSystemEffectiveEndDate desc"|"mdfSystemEffectiveStartDate"|"mdfSystemEffectiveStartDate desc"|"mdfSystemEntityId"|"mdfSystemEntityId desc"|"mdfSystemLastModifiedBy"|"mdfSystemLastModifiedBy desc"|"mdfSystemLastModifiedDate"|"mdfSystemLastModifiedDate desc"|"mdfSystemLastModifiedDateWithTZ"|"mdfSystemLastModifiedDateWithTZ desc"|"mdfSystemObjectType"|"mdfSystemObjectType desc"|"mdfSystemRecordId"|"mdfSystemRecordId desc"|"mdfSystemRecordStatus"|"mdfSystemRecordStatus desc"|"mdfSystemStatus"|"mdfSystemStatus desc"|"mdfSystemTransactionSequence"|"mdfSystemTransactionSequence desc"|"mdfSystemVersionId"|"mdfSystemVersionId desc"|"reason"|"reason desc")[] \$orderby?;
    # Include count of items, see [OData Count](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    boolean \$count?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("Position_code"|"Position_effectiveStartDate"|"code"|"createdBy"|"createdDateTime"|"gaEndJobInfoId"|"gaEventReason"|"gaStartJobInfoId"|"lastModifiedBy"|"lastModifiedDateTime"|"loaTimeType"|"mdfSystemCreatedBy"|"mdfSystemCreatedDate"|"mdfSystemEffectiveEndDate"|"mdfSystemEffectiveStartDate"|"mdfSystemEntityId"|"mdfSystemLastModifiedBy"|"mdfSystemLastModifiedDate"|"mdfSystemLastModifiedDateWithTZ"|"mdfSystemObjectType"|"mdfSystemRecordId"|"mdfSystemRecordStatus"|"mdfSystemStatus"|"mdfSystemTransactionSequence"|"mdfSystemVersionId"|"reason")[] \$select?;
};

public type CreatedRightToReturn record {
    RightToReturn d?;
};

# Represents the Headers record for the operation: deleteRightToReturn
public type DeleteRightToReturnHeaders record {
    # ETag
    string If\-Match?;
};

public type SecondaryAssignments record {
    string effectiveStartDate?;
    string externalCode?;
    RelatedCollectionSFOData_SecondaryAssignmentsItem allSfProcesses?;
};

public type Wrapper_1 record {
    CollectionofSecondaryAssignments d?;
};

# Represents the Headers record for the operation: deleteSecondaryAssignments
public type DeleteSecondaryAssignmentsHeaders record {
    # ETag
    string If\-Match?;
};

public type RightToReturn record {
    string Position_code?;
    string Position_effectiveStartDate?;
    string code?;
};

public type CollectionofRightToReturn record {
    RightToReturn[] results?;
};

public type Wrapper_2 record {
    CollectionofRightToReturn d?;
};

public type Wrapper_3 record {
    CollectionofEmpGlobalAssignment d?;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    http:CredentialsConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

# Represents the Queries record for the operation: getSecondaryAssignments
public type GetSecondaryAssignmentsQueries record {
    # Expand related entities, see [OData Expand](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("*"|"allSfProcesses")[] \$expand?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("createdBy"|"createdDate"|"createdDateTime"|"effectiveEndDate"|"effectiveStartDate"|"externalCode"|"lastModifiedBy"|"lastModifiedDate"|"lastModifiedDateTime"|"lastModifiedDateWithTZ"|"mdfSystemEntityId"|"mdfSystemObjectType"|"mdfSystemRecordId"|"mdfSystemRecordStatus"|"mdfSystemStatus"|"mdfSystemTransactionSequence"|"mdfSystemVersionId")[] \$select?;
};

public type Wrapper record {
    CollectionofSecondaryAssignmentsItem d?;
};

# Represents the Queries record for the operation: getSecondaryAssignmentsItem
public type GetSecondaryAssignmentsItemQueries record {
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("SecondaryAssignments_effectiveStartDate"|"SecondaryAssignments_externalCode"|"createdBy"|"createdDate"|"createdDateTime"|"externalCode"|"lastModifiedBy"|"lastModifiedDate"|"lastModifiedDateTime"|"lastModifiedDateWithTZ"|"mdfSystemEffectiveEndDate"|"mdfSystemEffectiveStartDate"|"mdfSystemEntityId"|"mdfSystemObjectType"|"mdfSystemRecordId"|"mdfSystemRecordStatus"|"mdfSystemStatus"|"mdfSystemTransactionSequence"|"mdfSystemVersionId"|"usersSysId")[] \$select?;
};

public type CollectionofEmpGlobalAssignment record {
    EmpGlobalAssignment[] results?;
};

# Represents the Queries record for the operation: getEmpGlobalAssignment
public type GetEmpGlobalAssignmentQueries record {
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("assignmentClass"|"assignmentType"|"createdBy"|"createdDateTime"|"createdOn"|"endDate"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"payrollEndDate"|"personIdExternal"|"plannedEndDate"|"startDate"|"userId")[] \$select?;
};

public type EmpGlobalAssignment record {
    EmpGlobalAssignment d?;
};

public type CreatedSecondaryAssignmentsItem record {
    SecondaryAssignmentsItem d?;
};

# Represents the Queries record for the operation: listEmpGlobalAssignments
public type ListEmpGlobalAssignmentsQueries record {
    # Skip the first n items, see [OData Paging - Skip](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$skip?;
    # Show only the first n items, see [OData Paging - Top](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$top = 20;
    # Filter items by property values, see [OData Filtering](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$filter?;
    # Search items by search phrases, see [OData Searching](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$search?;
    # Order items by property values, see [OData Sorting](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("assignmentClass"|"assignmentClass desc"|"assignmentType"|"assignmentType desc"|"createdBy"|"createdBy desc"|"createdDateTime"|"createdDateTime desc"|"createdOn"|"createdOn desc"|"endDate"|"endDate desc"|"lastModifiedBy"|"lastModifiedBy desc"|"lastModifiedDateTime"|"lastModifiedDateTime desc"|"lastModifiedOn"|"lastModifiedOn desc"|"payrollEndDate"|"payrollEndDate desc"|"personIdExternal"|"personIdExternal desc"|"plannedEndDate"|"plannedEndDate desc"|"startDate"|"startDate desc"|"userId"|"userId desc")[] \$orderby?;
    # Include count of items, see [OData Count](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    boolean \$count?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("assignmentClass"|"assignmentType"|"createdBy"|"createdDateTime"|"createdOn"|"endDate"|"lastModifiedBy"|"lastModifiedDateTime"|"lastModifiedOn"|"payrollEndDate"|"personIdExternal"|"plannedEndDate"|"startDate"|"userId")[] \$select?;
};

# Represents the Headers record for the operation: deleteSecondaryAssignmentsItem
public type DeleteSecondaryAssignmentsItemHeaders record {
    # ETag
    string If\-Match?;
};

# Represents the Queries record for the operation: getRightToReturn
public type GetRightToReturnQueries record {
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("Position_code"|"Position_effectiveStartDate"|"code"|"createdBy"|"createdDateTime"|"gaEndJobInfoId"|"gaEventReason"|"gaStartJobInfoId"|"lastModifiedBy"|"lastModifiedDateTime"|"loaTimeType"|"mdfSystemCreatedBy"|"mdfSystemCreatedDate"|"mdfSystemEffectiveEndDate"|"mdfSystemEffectiveStartDate"|"mdfSystemEntityId"|"mdfSystemLastModifiedBy"|"mdfSystemLastModifiedDate"|"mdfSystemLastModifiedDateWithTZ"|"mdfSystemObjectType"|"mdfSystemRecordId"|"mdfSystemRecordStatus"|"mdfSystemStatus"|"mdfSystemTransactionSequence"|"mdfSystemVersionId"|"reason")[] \$select?;
};

public type ModifiedRightToReturn record {
    RightToReturn d?;
};

public type ModifiedSecondaryAssignmentsItem record {
    SecondaryAssignmentsItem d?;
};

# Represents the Queries record for the operation: listSecondaryAssignmentss
public type ListSecondaryAssignmentssQueries record {
    # Skip the first n items, see [OData Paging - Skip](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$skip?;
    # Show only the first n items, see [OData Paging - Top](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    int \$top = 20;
    # Filter items by property values, see [OData Filtering](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$filter?;
    # Search items by search phrases, see [OData Searching](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    string \$search?;
    # Order items by property values, see [OData Sorting](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("createdBy"|"createdBy desc"|"createdDate"|"createdDate desc"|"createdDateTime"|"createdDateTime desc"|"effectiveEndDate"|"effectiveEndDate desc"|"effectiveStartDate"|"effectiveStartDate desc"|"externalCode"|"externalCode desc"|"lastModifiedBy"|"lastModifiedBy desc"|"lastModifiedDate"|"lastModifiedDate desc"|"lastModifiedDateTime"|"lastModifiedDateTime desc"|"lastModifiedDateWithTZ"|"lastModifiedDateWithTZ desc"|"mdfSystemEntityId"|"mdfSystemEntityId desc"|"mdfSystemObjectType"|"mdfSystemObjectType desc"|"mdfSystemRecordId"|"mdfSystemRecordId desc"|"mdfSystemRecordStatus"|"mdfSystemRecordStatus desc"|"mdfSystemStatus"|"mdfSystemStatus desc"|"mdfSystemTransactionSequence"|"mdfSystemTransactionSequence desc"|"mdfSystemVersionId"|"mdfSystemVersionId desc")[] \$orderby?;
    # Expand related entities, see [OData Expand](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("*"|"allSfProcesses")[] \$expand?;
    # Include count of items, see [OData Count](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    boolean \$count?;
    # Select properties to be returned, see [OData Select](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)
    ("createdBy"|"createdDate"|"createdDateTime"|"effectiveEndDate"|"effectiveStartDate"|"externalCode"|"lastModifiedBy"|"lastModifiedDate"|"lastModifiedDateTime"|"lastModifiedDateWithTZ"|"mdfSystemEntityId"|"mdfSystemObjectType"|"mdfSystemRecordId"|"mdfSystemRecordStatus"|"mdfSystemStatus"|"mdfSystemTransactionSequence"|"mdfSystemVersionId")[] \$select?;
};
