name: Publish Single Connector to the Ballerina Dev\Stage Central

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select Environment
        required: true
        options:
          - DEV CENTRAL
          - STAGE CENTRAL
      connector:
        type: choice
        description: Select Connector
        required: true
        options:
          - ecadvances
          - ecalternativecostdistribution
          - ecapprenticemanagement
          - eccompensationinformation
          - ecdismissalprotection
          - ecemployeecentralpayroll
          - ecemployeeprofile
          - ecemploymentinformation
          - ecfoundationorganization
          - ecglobalassignment
          - ecglobalbenefits
          - ecincometaxdeclaration
          - ecmasterdatareplication
          - ecpaymentinformation
          - ecpayrolltimesheets
          - ecpersonalinformation
          - ecpositionmanagement
          - ecskillsmanagement
          - ectimeoff
          - ecworkflow
          - employeecentralec

jobs:
  call_workflow:
    name: Run Dev\Stage Central Publish Workflow
    if: ${{ github.repository_owner == 'ballerina-platform' }}
    uses: ballerina-platform/ballerina-library/.github/workflows/s4hana-dev-stage-central-single-publish-template.yml@main
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      hana-connector-group: employeecentral
      hana-connector-name: ${{ inputs.connector }}
